version: '3.4'

services:
  ibcpapi:
    image: ibcpapi
    container_name: ibcpapi
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../..:/home/appuser/host
      - /tmp/.X11-unix:/tmp/.X11-unix
    cpus: 15
    command: ["sleep", "infinity"]
    ports:
      - "5000:5000"
    environment:
      - DISPLAY=:1
      - QT_DEBUG_PLUGINS=1
      - TZ=Australia/Brisbane
    privileged: true
    devices:
      - "/dev/dri/card0:/dev/dri/card0"
